### PR TITLE
scope: allow same-name options from different scopes

### PR DESCRIPTION
**Pull request by MarcelCoding**
depends https://github.com/NuschtOS/ixx/pull/32

### CODE REVIEW

**Comment by MarcelCoding** [comment]
@SuperSandro2000 ixx PR now merged and release created.

**Comment by SuperSandro2000** [comment]
the nix hash needs an update

**Comment by SuperSandro2000** [comment]
Also should we add an easy to spot indicator from which scope the options are? From the description you would need to guess which options is from which scope.

**Comment by MarcelCoding** [comment]
Aready done - have a look on the preview deployment.

**Comment by SuperSandro2000** [comment]
Should clicking the scope change the search scope on the left?

**Pull request merged**
